---
- name: Setup Hacking Lab VM
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: naughtrobot
        state: present
        shell: /bin/bash
        password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname) }}"
        groups: "sudo"
        append: yes
    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: naughtrobot
        state: present
        key: https://github.com/NaughtRobot/automagic-jank/blob/main/CaC/Ansible/SSHKeys/naughtrobot.key.pub