---
- name: Setup Hacking Lab VM
  hosts: localhost
  connection: local
  become: true
  vars:
    user: naughtrobot
  tasks:
    - name: Update and Upgrade Apt Packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Add hushlogin File to /etc/skel
      file:
        path: "/etc/skel/.hushlogin"
        state: touch
    - name: Create User
      ansible.builtin.user:
        name: "{{ user }}"
        state: present
        shell: /usr/bin/zsh
        password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname) | password_hash('sha512') }}"
        create_home: true
        skeleton: /etc/skel
        groups: "sudo"
        append: yes
    - name: Deploy SSH Public Key
      ansible.posix.authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ lookup('file', './SSHKeys/' + user + '.key.pub') }}"
    - name: Allow "sudo" Without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
    - name: Install Packages
      apt: 
        name: 
          - kali-linux-headless
          - openvpn
        state: latest
        cache_valid_time: 86400