---
- name: "Hack The Box Lab Setup"
  hosts: "localhost"
  connection: "local"
  vars:
    users:
      - "naughtrobot"
  tasks:
    - name: "Create user accounts and add users to groups"
      user:
        name: "{{ item }}"
        groups: "sudo"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'SSHKeys/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"